services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://test:test@db:5432/library
      - PORT_MICROSERVICE=8080
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres
    container_name: library
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
